# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11539038f4fb225b9944078016808e718841d7ce65b02d7ca42d39d4f2d55daed0c608e7742ad5d1522cd6f9ff9f529d4da3e4b5205163c4e262e571e66089fb

test:
  secret_key_base: 401070ee425298eb57865132f182a0c3a9f2c39f4a45cce91cf2c2c77ac7139a973c5d05f7c33a016cb0c9afbe9361962c5aa9271896d5c2b54423ca8dc815e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
